#!/usr/bin/env python3
"""Generate API_INVENTORY.md - a coverage table of every imported
operation/endpoint and whether it's currently exercised by an automatic
test, gated behind ALLOW_MUTATIONS, or excluded (with why).

Run: python3 tools/generate_inventory.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.spec.operations import OPERATIONS  # noqa: E402
from src.spec.endpoints import ENDPOINTS  # noqa: E402


def main():
    from tests.generated.test_operations import (
        EXCLUDED_QUERY_NAMES,
        KNOWN_BUGS,
    )
    from tests.generated.test_endpoints import (
        EXCLUDED_WITH_REASON,
        SAFE_READ_POST_NAMES,
    )

    lines = ["# API Inventory (generated by tools/generate_inventory.py)", ""]
    lines.append(f"Imported from `postman/collection_raw.json`: "
                 f"{len(OPERATIONS)} GraphQL operations, {len(ENDPOINTS)} REST endpoints.")
    lines.append("")

    lines.append("## GraphQL operations")
    lines.append("")
    lines.append("| Service | Operation | Kind | Status |")
    lines.append("|---|---|---|---|")
    for op in sorted(OPERATIONS, key=lambda o: (o.service, o.name)):
        key = (op.service, op.name)
        if op.kind == "mutation":
            status = "gated (ALLOW_MUTATIONS)"
        elif op.name in EXCLUDED_QUERY_NAMES:
            status = f"EXCLUDED - {EXCLUDED_QUERY_NAMES[op.name]}"
        elif key in KNOWN_BUGS:
            status = "known_bug (xfail)"
        else:
            status = "covered (auto)"
        lines.append(f"| {op.service} | {op.name} | {op.kind} | {status} |")

    lines.append("")
    lines.append("## REST endpoints")
    lines.append("")
    lines.append("| Service | Endpoint | Method | Status |")
    lines.append("|---|---|---|---|")
    for ep in sorted(ENDPOINTS, key=lambda e: (e.service, e.name)):
        if ep.name in EXCLUDED_WITH_REASON:
            status = f"EXCLUDED - {EXCLUDED_WITH_REASON[ep.name]}"
        elif ep.method == "GET" or ep.name in SAFE_READ_POST_NAMES:
            status = "covered (auto)"
        else:
            status = "UNCLASSIFIED"
        lines.append(f"| {ep.service} | {ep.name} | {ep.method} | {status} |")

    (ROOT / "API_INVENTORY.md").write_text("\n".join(lines) + "\n")
    print(f"Wrote {ROOT / 'API_INVENTORY.md'}")


if __name__ == "__main__":
    main()
